version: 2.1
jobs:
  qa:
    docker:
      - image: cimg/node:16.17
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: "Install"
          command: |
            yarn install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: "Lint"
          command: |
            yarn lint
      - run:
          name: "Test"
          command: |
            yarn test
      - run:
          name: "Coverage"
          command: |
            yarn test:coverage
workflows:
  build:
    jobs:
      - qa
